accounts/urls.py
from django.conf.urls import url
from accounts import views

from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
    )

urlpatterns = [
    url(r'^login/$', login, {'template_name':'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name':'accounts/logout.html'}, name='logout'),
    url(r'^quick_register/$', views.quick_register, name='quick_register'),
    url(r'^sign_up/$', views.signup, name='signup'),
    url(r'^razoweblogshuby/$', views.razoweblogshuby, name='razoweblogshuby'),

    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset_password/$', password_reset, {'template_name': 'accounts/reset_password.html','email_template_name':'accounts/reset_password_email.html', 'post_reset_redirect':'accounts:password_reset_done'}, name='reset_password'),
    url(r'^reset_password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm,{'post_reset_redirect':'accounts:password_reset_complete', 'template_name':'accounts/reset_password_complete.html'},name='password_reset_confirm'),
    url(r'^reset_password/complete/$', password_reset_complete,{'template_name':'accounts/reset_password_confirm.html'}, name='password_reset_complete'),
    url(r'^settings$', views.settings, name='settings'),
]

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create,name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

weblogshub/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from weblogshub import views as ngo_views #to make it more explicit we used 'as'
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', ngo_views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^blogger/', include('blogger.urls', namespace='blogger')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^home/', ngo_views.home, name='home'),
]

              # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

NATURE_CHOICES = (
    ('Blogger', 'Blogger'),
)

class BaseInfoUser(models.Model):
    user = models.OneToOneField(User)
    # profile_id = models.SlugField(unique=True,)
    nature = models.CharField(max_length=20, choices=NATURE_CHOICES,default='Blogger')

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        # self.item_id = uniqueCodeGenerator()
        # print('Base info jst got created and profile_id is ',self.profile_id)
        super(BaseInfoUser, self).save(*args, **kwargs)


@receiver(post_save, sender=User)
def create_baseinfouser(sender, instance, created, **kwargs):
    if created:
        BaseInfoUser.objects.create(user=instance, pk=instance.pk)



# from django.db import models
# from django.contrib.auth.models import User
# from django.db.models.signals import post_save
# from django.dispatch import receiver
# from utilities import uniqueCodeGenerator
#
#
# NATURE_CHOICES = (
#     ('OFFICER', 'OFFICER'),
#     ('RECEIVER', 'RECEIVER'),
#     ('VOLUNTEER', 'VOLUNTEER'),
# )
#
# class BaseInfoUser(models.Model):
#     user = models.OneToOneField(User)
#     # profile_id = models.SlugField(unique=True,)
#     nature = models.CharField(max_length=20, choices=NATURE_CHOICES,null=True,blank=True)
#
#     def __str__(self):
#         return self.user.username
#
#     def save(self, *args, **kwargs):
#         self.item_id = uniqueCodeGenerator()
#         # print('Base info jst got created and profile_id is ',self.profile_id)
#         super(BaseInfoUser, self).save(*args, **kwargs)
#
#
# @receiver(post_save, sender=User)
# def create_baseinfouser(sender, instance, created, **kwargs):
#     if created:
#         BaseInfoUser.objects.create(user=instance, pk=instance.pk)
#

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


#
# class Register_NowForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username','email',]
from accounts.models import BaseInfoUser
# from donator.models import BloggerProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name','password')

class BaseUserInfoForm(forms.ModelForm):
    class Meta:
        model = BaseInfoUser
        fields = ('nature',)



from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError


class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']

        )
        return user


accounts/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import PasswordChangeForm
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from accounts.models import BaseInfoUser
from blogger.models import BloggerProfile
from weblogshub.settings import EMAIL_HOST_USER
from .forms import BaseUserInfoForm, UserForm
#it used to be DonatorProfileForm so check it if it has a differenc content in previous that migh create  issue.
from django.contrib.auth.forms import UserCreationForm
from accounts.forms import CustomUserCreationForm

#...
def signup(request):
    if request.method == 'POST':
        f = CustomUserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            username = f.cleaned_data['username']
            raw_password = f.cleaned_data['password1']
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            profile, create = BloggerProfile.objects.get_or_create(user=request.user, pk=request.user.pk)
            if create is True:
                profile.email = f.cleaned_data['email']
                profile.save()
            print('profile.name-->', profile.name)
        else:
            messages.info(request,"Something went wrong please fill out the details once more. THank you!")
            return redirect(reverse('accounts:signup'))
            # send_mail(subject, message, from_email, to_list, fail_silently=True)
        subject = 'We thank you for signing up'
        message = 'YOu have successfully signed up!./n Thank you for joining us!./n YOu will get an email to setup your password very very soon...'
        from_email = EMAIL_HOST_USER
        to_list = [f.cleaned_data['email'], 'deepaksingh.18feb@gmail.com', ]
        send_mail(subject, message, from_email, to_list, fail_silently=True)
        print('email is just sent')
        return redirect('/posts/')
    else:
        f = CustomUserCreationForm()

    return render(request, 'accounts/signup.html', {'form': f})

def settings(request):

    return render(request,'accounts/settings.html')
    pass


def razoweblogshuby(request):

    return render(request,'accounts/razoweblogshuby.html',)

#CHECK THIS ONE OUT..
def quick_register(request):
    if request.method == 'POST':
        uf = UserCreationForm(request.POST)
        bf = BaseUserInfoForm(request.POST)
        print(request.POST)
        print('uf.is_valid()-->',uf.is_valid(),'bf.is_valid()-->',bf.is_valid())
        if uf.is_valid() and bf.is_valid():
            # username = uf.cleaned_data.get('username')
            # raw_password = uf.cleaned_data.get('password')
            # user = authenticate(username=username, password=raw_password)
            # login(request, user)
            user = uf.save()
            baseinfo_obj = BaseInfoUser.objects.get(user=user)
            baseinfo_obj.nature = bf.cleaned_data['nature']
            baseinfo_obj.save()
            print('baseinfo_obj.nature-->', baseinfo_obj.nature)
            if baseinfo_obj.nature == 'Blogger':
                print('user-->',user)
                profile, create = BloggerProfile.objects.get_or_create(user=user,pk=request.user.pk)
                if create is True:
                    profile.name = uf.cleaned_data['first_name'] + uf.cleaned_data['last_name']
                    profile.email = uf.cleaned_data['email']
                    profile.save()
                print('profile.name-->', profile.name)
        #send_mail(subject, message, from_email, to_list, fail_silently=True)
        subject = 'We thank you for signing up'
        message = 'YOu have successfully signed up!./n Thank you for joining us!./n YOu will get an email to setup your password very very soon...'
        from_email = EMAIL_HOST_USER
        to_list = [uf.cleaned_data['email'],'deepaksingh.18feb@gmail.com',]
        send_mail(subject,message,from_email,to_list,fail_silently=True)
        print('email is just sent')
        return redirect('/posts/')
    else:
        uf = UserCreationForm()
        bf = BaseUserInfoForm(request.POST)
        return render(request, 'accounts/reg_form.html', {'user_form': uf,'baseinfo_form':bf})






def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
        return redirect(reverse(viewname='posts:list'))
    else:
        form = PasswordChangeForm(user=request.user)
        return render(request,'accounts/change_password.html',{'form':form})

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <h1>Change Password</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    </div>
{% endblock %}

accounts/templates/accounts/home.html
{#{% extends 'base.html' %}#}
{% block content %}
    <div class="container">
        <h1>Welcome to Home</h1>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Welcome to Login Page</h1>
        <p>You can login here</p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
            </form>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <h1>Logged Out</h1>
        <p>You are Successfully Logged Out</p>
        <a href="{% url 'accounts:login' %}">Login</a>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Profile Page</h1>
        {% if profile.image %}
        <img src="{{ profile.image.url }}" width="100">
        {% endif %}
        <p>User - {{ user }}</p>
        <p>Username - {{ user.username }}</p>
        <p>Email - {{ profile.email }}</p>
        <p>Name - {{ profile.name }}</p>
        <p>Address - {{ profile.location }}</p>
        <p>Phone - {{ profile.phone }}</p>
        <p>Description - {{ profile.bio }}</p>
    </div>
{% endblock %}

accounts/templates/accounts/razorpay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>

    <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!--loading css file-->
        {% load static %}
        <link type="text/css" rel="stylesheet" href={% static 'accounts/style.css' %}/>
        <title>Base</title>
</head>
<body>
<h1>Razoweblogshuby here...</h1>
    <form action="/purchase" method="POST">
<!-- Note that the amount is in paise = 50 INR -->
<script
    src="https://checkout.razoweblogshuby.com/v1/checkout.js"
    data-key="rzp_test_RKTrD4nEmHtloG"
    data-amount="100"
    data-buttontext="Pay with Razoweblogshuby"
    data-name="weblogshub SIGN UP"
    data-description="Purchase Description"
    data-image="https://your-awesome-site.com/your_logo.jpg"
    data-prefill.name="Harshil Mathur"
    data-prefill.email="deepaksingh.18feb@gmail.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" value="Hidden Element" name="hidden">
</form>

</body>

</html>

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>Register</h1>
            {% if profile_form %}
                {{ profile_form.as_p }}
            {% endif %}
            {{ user_form.as_p }}
            {{ baseinfo_form.as_p }}
        <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/regiter_djangoform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>regiter_djangoform</title>
</head>
<body>
<h3>regiter_djangoform..</h3>
<form action="" method="post">{% csrf_token %}
    {{ register_form.as_p }}
    {{ profile_form.as_p }}
<button type="submit">Submit</button>
</form>

</body>
</html>

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <h1>Enter New Password</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <h1>Password Reset Complete</h1>
    <P>Your password is reset. You can go ahead and login now!</P>
    <a href="{% url 'accounts:login' %}">Login</a>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <h1>Password reset sent</h1>
    <P>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.  If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</P>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html

        {% load i18n %}{% autoescape off %}
        {% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

        {% trans "Please go to the following page and choose a new password:" %}
        {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
        {% endblock %}
        {% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

        {% trans "Thanks for using our site!" %}

        {% blocktrans %}The {{ site_name }} team{% endblocktrans %}
        {% endautoescape %}


accounts/templates/accounts/settings.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
             {% if user.BloggerProfile %}
              <h4>Donator Profile Settings</h4>
                     <li><a href="{% url 'donator:donator_profile_update' user.BloggerProfile.pk %}">Edit Donator Profile</a></li>
                {% endif %}

          <br>
                {% if user.ClientProfile %}
                    <h4>Receiver Profile Settings</h4>
                    <li><a href="{% url 'receiver:receiver_ClientProfile_update' user.id %}">Edit Receiver Profile</a></li>
                  {% endif %}
          <br>


                {% if user.volunteerprofile %}
                    <h4>Volunteer Profile Settings</h4>
                    <li><a href="#">Edit Volunteer Profile</a></li>
                  {% endif %}

<h4>Donation Settings</h4>
<h4>Center Settings</h4>
<h4>Task Settings</h4>
<h4>Reminder Settings</h4>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
     <div class="login">

         {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <h1>Sign UP Here!</h1>

         <form method="post" >
             {% csrf_token %}
             <table>
                {{ form.as_table }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Register" /></td>
                </tr>
             </table>
         </form>
     </div>
</div>


{% endblock %}