blogger/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import api
from . import views

router = routers.DefaultRouter()
router.register(r'bloggerprofile', api.BloggerProfileViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    url(r'^api/v1/', include(router.urls)),
)

urlpatterns += (
    url(r'^myprofile/$', views.blogger_profile, name='blogger_profile'),
    # urls for BloggerProfile
    url(r'^bloggerprofile/$', views.BloggerProfileListView.as_view(), name='blogger_bloggerprofile_list'),
    url(r'^bloggerprofile/create/$', views.BloggerProfileCreateView.as_view(), name='blogger_bloggerprofile_create'),
    url(r'^bloggerprofile/detail/(?P<pk>\S+)/$', views.BloggerProfileDetailView.as_view(), name='blogger_bloggerprofile_detail'),
    url(r'^bloggerprofile/update/(?P<pk>\S+)/$', views.BloggerProfileUpdateView.as_view(), name='blogger_bloggerprofile_update'),
)

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create,name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

weblogshub/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from weblogshub import views as ngo_views #to make it more explicit we used 'as'
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', ngo_views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^blogger/', include('blogger.urls', namespace='blogger')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^home/', ngo_views.home, name='home'),
]

              # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogger/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField
from django.db.models import *
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.auth import models as auth_models
from django.db import models as models
from django_extensions.db import fields as extension_fields


class BloggerProfile(models.Model):

    # Fields
    name = CharField(max_length=100,null=True,blank=True)
    blogger_id = SlugField(null=True,blank=True)
    email = EmailField()
    phone = CharField(max_length=100,null=True,blank=True)
    city = CharField(max_length=100,null=True,blank=True)
    state = CharField(max_length=100,null=True,blank=True)
    pin = IntegerField(null=True,blank=True)
    image = ImageField(null=True,blank=True)
    claps = IntegerField(null=True,blank=True)
    birthdate = DateField(null=True,blank=True)
    bio = CharField(max_length=500, null=True,blank=True)
    created = DateField(auto_now_add=True)
    portfolio = URLField(null=True,blank=True)
    journ_with_us = URLField(null=True,blank=True)
    business_rate = CharField(max_length=100,null=True,blank=True)
    net_business = CharField(max_length=100,null=True,blank=True)

    # Relationship Fields
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return u'%s' % self.pk

    def get_absolute_url(self):
        return reverse('blogger:blogger_bloggerprofile_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('blogger:blogger_bloggerprofile_update', args=(self.pk,))

blogger/forms.py
from django import forms
from .models import BloggerProfile


class BloggerProfileForm(forms.ModelForm):
    class Meta:
        model = BloggerProfile
        fields = ['name', 'blogger_id', 'email', 'phone', 'city', 'state', 'pin', 'image', 'claps', 'birthdate', 'bio', 'portfolio', 'journ_with_us', 'business_rate', 'net_business', 'user']

blogger/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import BloggerProfile
from .forms import BloggerProfileForm

def blogger_profile(request):
    print('request.user.bloggerprofile.pk-->',request.user.bloggerprofile.pk)
    blogger_profile = BloggerProfile.objects.get(pk=request.user.bloggerprofile.pk)
    print(blogger_profile)
    context = {'object': blogger_profile,'user':request.user}
    return render(request, template_name='blogger/blogger_myprofile.html',context=context)



class BloggerProfileListView(ListView):
    model = BloggerProfile


class BloggerProfileCreateView(CreateView):
    model = BloggerProfile
    form_class = BloggerProfileForm


class BloggerProfileDetailView(DetailView):
    model = BloggerProfile


class BloggerProfileUpdateView(UpdateView):
    model = BloggerProfile
    form_class = BloggerProfileForm

blogger/templates/blogger/blogger_myprofile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'blogger:blogger_bloggerprofile_list' %}">BloggerProfile Listing</a></p>
<table class="table">
<tr><td>username</td><td>{{ object.user.username }}</td></tr>
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>blogger_id</td><td>{{ object.blogger_id }}</td></tr>
<tr><td>email</td><td>{{ object.email }}</td></tr>
<tr><td>phone</td><td>{{ object.phone }}</td></tr>
<tr><td>city</td><td>{{ object.city }}</td></tr>
<tr><td>state</td><td>{{ object.state }}</td></tr>
<tr><td>pin</td><td>{{ object.pin }}</td></tr>
<tr><td>image</td><td>{{ object.image }}</td></tr>
<tr><td>claps</td><td>{{ object.claps }}</td></tr>
<tr><td>birthdate</td><td>{{ object.birthdate }}</td></tr>
<tr><td>bio</td><td>{{ object.bio }}</td></tr>
<tr><td>created</td><td>{{ object.created }}</td></tr>
<tr><td>portfolio</td><td>{{ object.portfolio }}</td></tr>
<tr><td>journ_with_us</td><td>{{ object.journ_with_us }}</td></tr>
<tr><td>business_rate</td><td>{{ object.business_rate }}</td></tr>
<tr><td>net_business</td><td>{{ object.net_business }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit BloggerProfile</a>

{% endblock %}

blogger/templates/blogger/bloggerprofile_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'blogger:blogger_bloggerprofile_list' %}">BloggerProfile Listing</a></p>
<table class="table">
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>blogger_id</td><td>{{ object.blogger_id }}</td></tr>
<tr><td>email</td><td>{{ object.email }}</td></tr>
<tr><td>phone</td><td>{{ object.phone }}</td></tr>
<tr><td>city</td><td>{{ object.city }}</td></tr>
<tr><td>state</td><td>{{ object.state }}</td></tr>
<tr><td>pin</td><td>{{ object.pin }}</td></tr>
<tr><td>image</td><td>{{ object.image }}</td></tr>
<tr><td>claps</td><td>{{ object.claps }}</td></tr>
<tr><td>birthdate</td><td>{{ object.birthdate }}</td></tr>
<tr><td>bio</td><td>{{ object.bio }}</td></tr>
<tr><td>created</td><td>{{ object.created }}</td></tr>
<tr><td>portfolio</td><td>{{ object.portfolio }}</td></tr>
<tr><td>journ_with_us</td><td>{{ object.journ_with_us }}</td></tr>
<tr><td>business_rate</td><td>{{ object.business_rate }}</td></tr>
<tr><td>net_business</td><td>{{ object.net_business }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit BloggerProfile</a>

{% endblock %}

blogger/templates/blogger/bloggerprofile_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'blogger:blogger_bloggerprofile_list' %}">BloggerProfile Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

blogger/templates/blogger/bloggerprofile_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'blogger:blogger_bloggerprofile_list' %}">BloggerProfile Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>name</td>
    <td>blogger_id</td>
    <td>email</td>
    <td>phone</td>
    <td>city</td>
    <td>state</td>
    <td>pin</td>
    <td>image</td>
    <td>claps</td>
    <td>birthdate</td>
    <td>bio</td>
    <td>created</td>
    <td>portfolio</td>
    <td>journ_with_us</td>
    <td>business_rate</td>
    <td>net_business</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.blogger_id }}</td>
    <td>{{ object.email }}</td>
    <td>{{ object.phone }}</td>
    <td>{{ object.city }}</td>
    <td>{{ object.state }}</td>
    <td>{{ object.pin }}</td>
    <td>{{ object.image }}</td>
    <td>{{ object.claps }}</td>
    <td>{{ object.birthdate }}</td>
    <td>{{ object.bio }}</td>
    <td>{{ object.created }}</td>
    <td>{{ object.portfolio }}</td>
    <td>{{ object.journ_with_us }}</td>
    <td>{{ object.business_rate }}</td>
    <td>{{ object.net_business }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'blogger:blogger_bloggerprofile_create' %}">Create new BloggerProfile</a>
{% endblock %}